"""Add comprehensive transaction fields for analysis and categorization

Revision ID: 491e21627439
Revises: 
Create Date: 2026-01-08 22:52:52.552367

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '491e21627439'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('transaction_datetime', sa.DateTime(), nullable=True))
    op.add_column('transactions', sa.Column('iso_currency_code', sa.String(), nullable=True))
    op.add_column('transactions', sa.Column('unofficial_currency_code', sa.String(), nullable=True))
    op.add_column('transactions', sa.Column('subtype', sa.String(), nullable=True))
    op.add_column('transactions', sa.Column('fees', sa.Numeric(precision=20, scale=2), nullable=True))
    op.add_column('transactions', sa.Column('cancel_transaction_id', sa.String(), nullable=True))
    op.add_column('transactions', sa.Column('is_cancelled', sa.Boolean(), nullable=True))
    op.add_column('transactions', sa.Column('location_city', sa.String(), nullable=True))
    op.add_column('transactions', sa.Column('location_region', sa.String(), nullable=True))
    op.add_column('transactions', sa.Column('location_country', sa.String(), nullable=True))
    op.add_column('transactions', sa.Column('location_address', sa.String(), nullable=True))
    op.add_column('transactions', sa.Column('location_postal_code', sa.String(), nullable=True))
    op.add_column('transactions', sa.Column('user_category', sa.String(), nullable=True))
    op.add_column('transactions', sa.Column('tags', sa.JSON(), nullable=True))
    op.add_column('transactions', sa.Column('notes', sa.Text(), nullable=True))
    op.add_column('transactions', sa.Column('is_tax_deductible', sa.Boolean(), nullable=True))
    op.add_column('transactions', sa.Column('tax_category', sa.String(), nullable=True))
    op.add_column('transactions', sa.Column('is_recurring', sa.Boolean(), nullable=True))
    op.add_column('transactions', sa.Column('recurring_pattern', sa.String(), nullable=True))
    op.add_column('transactions', sa.Column('confidence_score', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('transactions', sa.Column('plaid_data', sa.JSON(), nullable=True))
    op.create_index('idx_transaction_category', 'transactions', ['category'], unique=False)
    op.create_index('idx_transaction_date_range', 'transactions', ['date', 'account_id'], unique=False)
    op.create_index('idx_transaction_merchant', 'transactions', ['merchant_name'], unique=False)
    op.create_index('idx_transaction_pending', 'transactions', ['is_pending'], unique=False)
    op.create_index('idx_transaction_recurring', 'transactions', ['is_recurring'], unique=False)
    op.create_index('idx_transaction_subtype', 'transactions', ['subtype'], unique=False)
    op.create_index('idx_transaction_ticker', 'transactions', ['ticker'], unique=False)
    op.create_index('idx_transaction_user_category', 'transactions', ['user_category'], unique=False)
    op.create_index(op.f('ix_transactions_category'), 'transactions', ['category'], unique=False)
    op.create_index(op.f('ix_transactions_is_cancelled'), 'transactions', ['is_cancelled'], unique=False)
    op.create_index(op.f('ix_transactions_is_pending'), 'transactions', ['is_pending'], unique=False)
    op.create_index(op.f('ix_transactions_is_recurring'), 'transactions', ['is_recurring'], unique=False)
    op.create_index(op.f('ix_transactions_merchant_name'), 'transactions', ['merchant_name'], unique=False)
    op.create_index(op.f('ix_transactions_subtype'), 'transactions', ['subtype'], unique=False)
    op.create_index(op.f('ix_transactions_type'), 'transactions', ['type'], unique=False)
    op.create_index(op.f('ix_transactions_user_category'), 'transactions', ['user_category'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_user_category'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_type'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_subtype'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_merchant_name'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_is_recurring'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_is_pending'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_is_cancelled'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_category'), table_name='transactions')
    op.drop_index('idx_transaction_user_category', table_name='transactions')
    op.drop_index('idx_transaction_ticker', table_name='transactions')
    op.drop_index('idx_transaction_subtype', table_name='transactions')
    op.drop_index('idx_transaction_recurring', table_name='transactions')
    op.drop_index('idx_transaction_pending', table_name='transactions')
    op.drop_index('idx_transaction_merchant', table_name='transactions')
    op.drop_index('idx_transaction_date_range', table_name='transactions')
    op.drop_index('idx_transaction_category', table_name='transactions')
    op.drop_column('transactions', 'plaid_data')
    op.drop_column('transactions', 'confidence_score')
    op.drop_column('transactions', 'recurring_pattern')
    op.drop_column('transactions', 'is_recurring')
    op.drop_column('transactions', 'tax_category')
    op.drop_column('transactions', 'is_tax_deductible')
    op.drop_column('transactions', 'notes')
    op.drop_column('transactions', 'tags')
    op.drop_column('transactions', 'user_category')
    op.drop_column('transactions', 'location_postal_code')
    op.drop_column('transactions', 'location_address')
    op.drop_column('transactions', 'location_country')
    op.drop_column('transactions', 'location_region')
    op.drop_column('transactions', 'location_city')
    op.drop_column('transactions', 'is_cancelled')
    op.drop_column('transactions', 'cancel_transaction_id')
    op.drop_column('transactions', 'fees')
    op.drop_column('transactions', 'subtype')
    op.drop_column('transactions', 'unofficial_currency_code')
    op.drop_column('transactions', 'iso_currency_code')
    op.drop_column('transactions', 'transaction_datetime')
    # ### end Alembic commands ###
