"""Add income and deposit tracking fields

Revision ID: 5a3b549b1ff2
Revises: 491e21627439
Create Date: 2026-01-08 22:56:28.056064

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a3b549b1ff2'
down_revision = '491e21627439'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('is_income', sa.Boolean(), nullable=True))
    op.add_column('transactions', sa.Column('is_deposit', sa.Boolean(), nullable=True))
    op.add_column('transactions', sa.Column('income_type', sa.String(), nullable=True))
    op.add_column('transactions', sa.Column('is_paystub', sa.Boolean(), nullable=True))
    op.add_column('transactions', sa.Column('paystub_period_start', sa.DateTime(), nullable=True))
    op.add_column('transactions', sa.Column('paystub_period_end', sa.DateTime(), nullable=True))
    op.create_index('idx_transaction_deposit', 'transactions', ['is_deposit'], unique=False)
    op.create_index('idx_transaction_income', 'transactions', ['is_income'], unique=False)
    op.create_index('idx_transaction_income_type', 'transactions', ['income_type'], unique=False)
    op.create_index('idx_transaction_paystub', 'transactions', ['is_paystub'], unique=False)
    op.create_index(op.f('ix_transactions_income_type'), 'transactions', ['income_type'], unique=False)
    op.create_index(op.f('ix_transactions_is_deposit'), 'transactions', ['is_deposit'], unique=False)
    op.create_index(op.f('ix_transactions_is_income'), 'transactions', ['is_income'], unique=False)
    op.create_index(op.f('ix_transactions_is_paystub'), 'transactions', ['is_paystub'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_is_paystub'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_is_income'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_is_deposit'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_income_type'), table_name='transactions')
    op.drop_index('idx_transaction_paystub', table_name='transactions')
    op.drop_index('idx_transaction_income_type', table_name='transactions')
    op.drop_index('idx_transaction_income', table_name='transactions')
    op.drop_index('idx_transaction_deposit', table_name='transactions')
    op.drop_column('transactions', 'paystub_period_end')
    op.drop_column('transactions', 'paystub_period_start')
    op.drop_column('transactions', 'is_paystub')
    op.drop_column('transactions', 'income_type')
    op.drop_column('transactions', 'is_deposit')
    op.drop_column('transactions', 'is_income')
    # ### end Alembic commands ###
