"""add_expense_tracking_fields

Revision ID: b2e48200fa3b
Revises: 5a3b549b1ff2
Create Date: 2026-01-09 01:21:39.331479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2e48200fa3b'
down_revision = '5a3b549b1ff2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('primary_category', sa.String(), nullable=True))
    op.add_column('transactions', sa.Column('detailed_category', sa.String(), nullable=True))
    op.add_column('transactions', sa.Column('is_expense', sa.Boolean(), nullable=True))
    op.add_column('transactions', sa.Column('expense_category', sa.String(), nullable=True))
    op.add_column('transactions', sa.Column('expense_type', sa.String(), nullable=True))
    op.create_index('idx_transaction_detailed_category', 'transactions', ['detailed_category'], unique=False)
    op.create_index('idx_transaction_expense', 'transactions', ['is_expense'], unique=False)
    op.create_index('idx_transaction_expense_category', 'transactions', ['expense_category'], unique=False)
    op.create_index('idx_transaction_primary_category', 'transactions', ['primary_category'], unique=False)
    op.create_index(op.f('ix_transactions_detailed_category'), 'transactions', ['detailed_category'], unique=False)
    op.create_index(op.f('ix_transactions_expense_category'), 'transactions', ['expense_category'], unique=False)
    op.create_index(op.f('ix_transactions_expense_type'), 'transactions', ['expense_type'], unique=False)
    op.create_index(op.f('ix_transactions_is_expense'), 'transactions', ['is_expense'], unique=False)
    op.create_index(op.f('ix_transactions_primary_category'), 'transactions', ['primary_category'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_primary_category'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_is_expense'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_expense_type'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_expense_category'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_detailed_category'), table_name='transactions')
    op.drop_index('idx_transaction_primary_category', table_name='transactions')
    op.drop_index('idx_transaction_expense_category', table_name='transactions')
    op.drop_index('idx_transaction_expense', table_name='transactions')
    op.drop_index('idx_transaction_detailed_category', table_name='transactions')
    op.drop_column('transactions', 'expense_type')
    op.drop_column('transactions', 'expense_category')
    op.drop_column('transactions', 'is_expense')
    op.drop_column('transactions', 'detailed_category')
    op.drop_column('transactions', 'primary_category')
    # ### end Alembic commands ###
